In [1]:
!pip install numpy 

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 2.8 MB/s eta 0:00:05
   ---- ----------------------------------- 1.3/12.6 MB 3.2 MB/s eta 0:00:04
   ------ --------------------------------- 2.1/12.6 MB 3.6 MB/s eta 0:00:03
   --------- ------------------------------ 3.1/12.6 MB 3.9 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.6 MB 4.1 MB/s eta 0:00:03
   --------------- ------------------------ 5.0/12.6 MB 4.0 MB/s eta 0:00:02
   ------------------ --------------------- 5.8/12.6 MB 4.0 MB/s eta 0:00:02
   -------------------- ------------------- 6.6/12.6 MB 4.0 MB/s eta 0:00:02
   ------------------------ --------------- 7.6/12.6 MB 4.0 MB/s eta 0:00:02
   -------------------------- ------------- 8.4/12.6 MB 4.1 MB/s eta 0:00:02
   ----------------------------- ---------- 9.2/12.6 MB 4.1 MB/s eta 0:00:01
   -------------------------------- ------- 10.2/12.6 MB 4.0 MB/s eta 0:00:01
   --

In [5]:
import numpy as np 
arr = np.array([2,12,2,3,4,6,8])
print(arr)
print(type(arr))
print(arr.shape)

[ 2 12  2  3  4  6  8]
<class 'numpy.ndarray'>
(7,)


In [7]:
arr2 = np.array([2,12,2,3,4,6,8])
arr2.reshape(1,7)

array([[ 2, 12,  2,  3,  4,  6,  8]])

In [8]:
# 2D array
arr3 = np.array([[2,12,2,3,4,6,8],[1,2,3,4,5,6,7]])
print(arr3)
print(arr3.shape)


[[ 2 12  2  3  4  6  8]
 [ 1  2  3  4  5  6  7]]
(2, 7)


In [10]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
print("Array : ",arr3)
print("size : ", arr3.size)
print("Shape : ", arr3.shape)
print("Dimension : ", arr3.ndim)
print("Data type : ", arr3.dtype)
print("item size : ", arr3.itemsize)



Array :  [[ 2 12  2  3  4  6  8]
 [ 1  2  3  4  5  6  7]]
size :  14
Shape :  (2, 7)
Dimension :  2
Data type :  int64
item size :  8


In [18]:
# Universal function 
arr4 = np.array([2,12,2,3])
print(np.sqrt(arr4))
print(np.exp(arr4))
print(np.sin(arr4))
print(np.log(arr4))

[1.41421356 3.46410162 1.41421356 1.73205081]
[7.38905610e+00 1.62754791e+05 7.38905610e+00 2.00855369e+01]
[ 0.90929743 -0.53657292  0.90929743  0.14112001]
[0.69314718 2.48490665 0.69314718 1.09861229]


In [29]:
arr5 = np.array([[2,12,2,3],[4,6,3,9],[9,7,5,2]])
print(arr5)
print(arr5[2][2])
print(arr5[0][0])
print(arr5[0:2,2:])
print(arr5[1:,2:])
arr5[1:]= 100
print(arr5)


[[ 2 12  2  3]
 [ 4  6  3  9]
 [ 9  7  5  2]]
5
2
[[2 3]
 [3 9]]
[[3 9]
 [5 2]]
[[  2  12   2   3]
 [100 100 100 100]
 [100 100 100 100]]


In [31]:
data = np.array([2,12,2,3])

mean = np.mean(data)
std_dev = np.std(data)

normalization = (data - mean) / std_dev
print("Normalization  = ",normalization )


Normalization  =  [-0.65388213  1.72387107 -0.65388213 -0.41610681]


In [34]:
median = np.median(data)
print("median : ",median)

variance = np.var(data)
print("variance : ",variance )

median :  2.5
variance :  17.6875


In [42]:
data>3
print(data[data>3])
data[(data>=2) & (data<=8)]

[12]


array([2, 2, 3])